import clsx from "clsx";
import { useId } from "react";
import { MARK, WORDMARK } from "./brand-paths";

/**
 * The SecureLens mark (flat): an S ribbon wrapped around a lens that holds
 * "</>". The ribbon and lens keep their brand colours in both themes; the
 * wordmark follows the --brand-* tokens. The geometry is generated by
 * brand/tools/build_brand.py — never redraw it here. For motion and depth see
 * BrandMark3D.
 */
function MarkShapes({ id }: { id: string }) {
  return (
    <>
      <defs>
        <mask id={`${id}-m`} maskUnits="userSpaceOnUse" x="0" y="0" width="64" height="64">
          <rect width="64" height="64" fill="#fff" />
          <circle cx={MARK.lens.cx} cy={MARK.lens.cy} r={MARK.lens.r + MARK.lens.gap} fill="#000" />
        </mask>
        <linearGradient id={`${id}-u`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor={MARK.colors.upper[0]} />
          <stop offset="1" stopColor={MARK.colors.upper[1]} />
        </linearGradient>
        <linearGradient id={`${id}-l`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor={MARK.colors.lower[0]} />
          <stop offset="1" stopColor={MARK.colors.lower[1]} />
        </linearGradient>
      </defs>
      <g mask={`url(#${id}-m)`}>
        <path d={MARK.lower} fill={`url(#${id}-l)`} />
        <path d={MARK.upper} fill={`url(#${id}-u)`} />
      </g>
      <circle cx={MARK.lens.cx} cy={MARK.lens.cy} r={MARK.lens.r} fill={MARK.colors.lens} />
      <circle
        cx={MARK.lens.cx}
        cy={MARK.lens.cy}
        r={MARK.lens.r - MARK.lens.ring}
        fill="none"
        stroke={MARK.colors.ring}
        strokeWidth={MARK.lens.ring}
      />
      <g fill="none" stroke={MARK.colors.glyph} strokeWidth={MARK.glyph} strokeLinecap="round" strokeLinejoin="round">
        {MARK.glyphs.map((d) => (
          <path key={d} d={d} />
        ))}
      </g>
    </>
  );
}

function useSvgId(prefix: string): string {
  return `${prefix}${useId().replace(/[^a-zA-Z0-9_-]/g, "")}`;
}

/** The symbol alone: compact headers, loaders, favicon-like placements. */
export function LogoMark({ className, title = "SecureLens AI" }: { className?: string; title?: string | null }) {
  const id = useSvgId("slm");
  const labelled = title !== null;
  return (
    <svg
      viewBox="0 0 64 64"
      className={clsx("shrink-0", className)}
      role={labelled ? "img" : undefined}
      aria-label={labelled ? title : undefined}
      aria-hidden={labelled ? undefined : true}
      focusable="false"
    >
      <MarkShapes id={id} />
    </svg>
  );
}

/** Symbol + SECURELENS wordmark with AI as a quieter descriptor. */
export function Logo({ className }: { className?: string }) {
  const id = useSvgId("sll");
  return (
    <svg
      viewBox={`0 0 ${WORDMARK.width} ${WORDMARK.height}`}
      className={clsx("shrink-0", className)}
      role="img"
      aria-label="SecureLens AI"
      focusable="false"
    >
      <g transform={`translate(${WORDMARK.markDx} 0)`}>
        <MarkShapes id={id} />
      </g>
      <path d={WORDMARK.name.d} fill="var(--brand-ink)" transform={`translate(${WORDMARK.name.x} ${WORDMARK.name.y})`} />
      <rect x={WORDMARK.rule.x} y={WORDMARK.rule.y} width={WORDMARK.rule.width} height={WORDMARK.rule.height} fill="var(--brand-rule)" />
      <path d={WORDMARK.ai.d} fill="var(--brand-accent)" transform={`translate(${WORDMARK.ai.x} ${WORDMARK.ai.y})`} />
    </svg>
  );
}
