"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 06:18:53.228630
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import securelens.models.base
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', securelens.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('locked_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_status_run_after', ['status', 'run_after'], unique=False)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_memberships_organization_id_user_id'))
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_criticality', sa.String(length=16), nullable=True),
    sa.Column('exposure', sa.String(length=24), nullable=False),
    sa.Column('gate_policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('finding_seq', sa.Integer(), nullable=False),
    sa.Column('ai_finding_seq', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_projects_organization_id_slug'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('security_tests',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('test_key', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attack_scenario', sa.Text(), nullable=False),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('ai_risk_category', sa.String(length=80), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_security_tests_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_security_tests_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_tests'))
    )
    with op.batch_alter_table('security_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_tests_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_tests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('uq_security_tests_builtin_key', ['test_key'], unique=True, postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
        batch_op.create_index('uq_security_tests_org_key', ['organization_id', 'test_key'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))

    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', securelens.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', securelens.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('revoked_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('ai_targets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_ai_targets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_targets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_targets'))
    )
    with op.batch_alter_table('ai_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_targets_project_id'), ['project_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('last_used_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_api_keys_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_api_keys_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_api_keys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_project_id'), ['project_id'], unique=False)

    op.create_table('integrations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_event_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_integrations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_integrations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_project_id'), ['project_id'], unique=False)

    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_project_members_project_id_user_id'))
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('repositories',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('default_branch', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_repositories_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories'))
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_project_id'), ['project_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_api_key_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_api_key_id'], ['api_keys.id'], name=op.f('fk_audit_logs_actor_api_key_id_api_keys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_org_created', ['organization_id', 'created_at'], unique=False)

    op.create_table('snapshots',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('upload_key', sa.String(length=300), nullable=True),
    sa.Column('upload_name', sa.String(length=300), nullable=True),
    sa.Column('parent_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('git_ref', sa.String(length=200), nullable=True),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_snapshots_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_snapshot_id'], ['snapshots.id'], name=op.f('fk_snapshots_parent_snapshot_id_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_snapshots_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_snapshots_repository_id_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots'))
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_repository_id'), ['repository_id'], unique=False)

    op.create_table('test_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('baseline_run_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['test_runs.id'], name=op.f('fk_test_runs_baseline_run_id_test_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_test_runs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_test_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['ai_targets.id'], name=op.f('fk_test_runs_target_id_ai_targets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_runs'))
    )
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_runs_target_id'), ['target_id'], unique=False)

    op.create_table('scans',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('baseline_scan_id', sa.Uuid(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('progress', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_index', sa.Float(), nullable=True),
    sa.Column('gate_status', sa.String(length=8), nullable=True),
    sa.Column('gate_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_scans_api_key_id_api_keys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['baseline_scan_id'], ['scans.id'], name=op.f('fk_scans_baseline_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scans_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scans_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_scans_repository_id_repositories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], name=op.f('fk_scans_snapshot_id_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('ix_scans_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_status'), ['status'], unique=False)

    op.create_table('dependencies',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('version_spec', sa.String(length=300), nullable=True),
    sa.Column('manifest_path', sa.String(length=1024), nullable=False),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('dev', sa.Boolean(), nullable=False),
    sa.Column('vuln_status', sa.String(length=32), nullable=False),
    sa.Column('advisory_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_dependencies_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependencies')),
    sa.UniqueConstraint('scan_id', 'ecosystem', 'name', 'version', 'manifest_path', name=op.f('uq_dependencies_scan_id_ecosystem_name_version_manifest_path'))
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index('ix_dependencies_name', ['ecosystem', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_scan_id'), ['scan_id'], unique=False)

    op.create_table('findings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('engine_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=8), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('vuln_class', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('verification', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exploitability', sa.String(length=20), nullable=False),
    sa.Column('cwe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('owasp', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('remediation_guidance', sa.Text(), nullable=False),
    sa.Column('references', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('first_seen_scan_id', sa.Uuid(), nullable=True),
    sa.Column('last_seen_scan_id', sa.Uuid(), nullable=True),
    sa.Column('first_seen_run_id', sa.Uuid(), nullable=True),
    sa.Column('last_seen_run_id', sa.Uuid(), nullable=True),
    sa.Column('first_seen_at', securelens.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', securelens.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_scan_id', sa.Uuid(), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('status_changed_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status_changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['test_runs.id'], name=op.f('fk_findings_first_seen_run_id_test_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_seen_scan_id'], ['scans.id'], name=op.f('fk_findings_first_seen_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_run_id'], ['test_runs.id'], name=op.f('fk_findings_last_seen_run_id_test_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_scan_id'], ['scans.id'], name=op.f('fk_findings_last_seen_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_findings_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_findings_repository_id_repositories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_scan_id'], ['scans.id'], name=op.f('fk_findings_resolved_by_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_changed_by_id'], ['users.id'], name=op.f('fk_findings_status_changed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['ai_targets.id'], name=op.f('fk_findings_target_id_ai_targets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('project_id', 'fingerprint', name=op.f('uq_findings_project_id_fingerprint')),
    sa.UniqueConstraint('project_id', 'public_id', name=op.f('uq_findings_project_id_public_id'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_engine_fingerprint'), ['engine_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_findings_project_status_severity', ['project_id', 'status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_vuln_class'), ['vuln_class'], unique=False)

    op.create_table('reports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('test_run_id', sa.Uuid(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('generated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_reports_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], name=op.f('fk_reports_test_run_id_test_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)

    op.create_table('retests',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('baseline_scan_id', sa.Uuid(), nullable=True),
    sa.Column('retest_scan_id', sa.Uuid(), nullable=True),
    sa.Column('baseline_run_id', sa.Uuid(), nullable=True),
    sa.Column('retest_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gate_status', sa.String(length=8), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['test_runs.id'], name=op.f('fk_retests_baseline_run_id_test_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['baseline_scan_id'], ['scans.id'], name=op.f('fk_retests_baseline_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_retests_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_retests_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retest_run_id'], ['test_runs.id'], name=op.f('fk_retests_retest_run_id_test_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retest_scan_id'], ['scans.id'], name=op.f('fk_retests_retest_scan_id_scans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retests'))
    )
    with op.batch_alter_table('retests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retests_retest_run_id'), ['retest_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retests_retest_scan_id'), ['retest_scan_id'], unique=False)

    op.create_table('scan_files',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_files_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_files')),
    sa.UniqueConstraint('scan_id', 'path', name=op.f('uq_scan_files_scan_id_path'))
    )
    with op.batch_alter_table('scan_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_files_scan_id'), ['scan_id'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_output_excerpt', sa.Text(), nullable=True),
    sa.Column('context_sha256', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_ai_analyses_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_ai_analyses_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_finding_id'), ['finding_id'], unique=False)

    op.create_table('finding_occurrences',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('test_run_id', sa.Uuid(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('start_col', sa.Integer(), nullable=True),
    sa.Column('end_col', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.String(length=300), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('scanners', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_occurrences_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_finding_occurrences_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], name=op.f('fk_finding_occurrences_test_run_id_test_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_occurrences')),
    sa.UniqueConstraint('finding_id', 'scan_id', name=op.f('uq_finding_occurrences_finding_id_scan_id')),
    sa.UniqueConstraint('finding_id', 'test_run_id', name=op.f('uq_finding_occurrences_finding_id_test_run_id'))
    )
    with op.batch_alter_table('finding_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_occurrences_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_occurrences_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_occurrences_test_run_id'), ['test_run_id'], unique=False)

    op.create_table('retest_results',
    sa.Column('retest_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('match_method', sa.String(length=16), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_retest_results_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retest_id'], ['retests.id'], name=op.f('fk_retest_results_retest_id_retests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retest_results')),
    sa.UniqueConstraint('retest_id', 'finding_id', name=op.f('uq_retest_results_retest_id_finding_id'))
    )
    with op.batch_alter_table('retest_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retest_results_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retest_results_retest_id'), ['retest_id'], unique=False)

    op.create_table('secret_findings',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('secret_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('masked_value', sa.String(length=200), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('detector', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_secret_findings_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_secret_findings_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_findings'))
    )
    with op.batch_alter_table('secret_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_findings_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secret_findings_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secret_findings_secret_hash'), ['secret_hash'], unique=False)

    op.create_table('test_results',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('security_test_id', sa.Uuid(), nullable=True),
    sa.Column('test_key', sa.String(length=40), nullable=False),
    sa.Column('test_version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('failure_layer', sa.String(length=24), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('observations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_test_results_finding_id_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], name=op.f('fk_test_results_run_id_test_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_test_id'], ['security_tests.id'], name=op.f('fk_test_results_security_test_id_security_tests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_results'))
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_run_id'), ['run_id'], unique=False)

    op.create_table('evidence',
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('location', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_evidence_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['finding_occurrences.id'], name=op.f('fk_evidence_occurrence_id_finding_occurrences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_occurrence_id'), ['occurrence_id'], unique=False)

    op.create_table('remediations',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('ai_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('source_scan_id', sa.Uuid(), nullable=True),
    sa.Column('base_sha256', sa.String(length=64), nullable=True),
    sa.Column('patch', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('applied_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('retest_scan_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', securelens.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', securelens.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_analyses.id'], name=op.f('fk_remediations_ai_analysis_id_ai_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['applied_snapshot_id'], ['snapshots.id'], name=op.f('fk_remediations_applied_snapshot_id_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_remediations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_remediations_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_remediations_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retest_scan_id'], ['scans.id'], name=op.f('fk_remediations_retest_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_scan_id'], ['scans.id'], name=op.f('fk_remediations_source_scan_id_scans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediations'))
    )
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediations_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediations_finding_id'))

    op.drop_table('remediations')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_occurrence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_run_id'))

    op.drop_table('test_results')
    with op.batch_alter_table('secret_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_findings_secret_hash'))
        batch_op.drop_index(batch_op.f('ix_secret_findings_scan_id'))
        batch_op.drop_index(batch_op.f('ix_secret_findings_finding_id'))

    op.drop_table('secret_findings')
    with op.batch_alter_table('retest_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retest_results_retest_id'))
        batch_op.drop_index(batch_op.f('ix_retest_results_finding_id'))

    op.drop_table('retest_results')
    with op.batch_alter_table('finding_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_occurrences_test_run_id'))
        batch_op.drop_index(batch_op.f('ix_finding_occurrences_scan_id'))
        batch_op.drop_index(batch_op.f('ix_finding_occurrences_finding_id'))

    op.drop_table('finding_occurrences')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_finding_id'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('scan_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_files_scan_id'))

    op.drop_table('scan_files')
    with op.batch_alter_table('retests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retests_retest_scan_id'))
        batch_op.drop_index(batch_op.f('ix_retests_retest_run_id'))
        batch_op.drop_index(batch_op.f('ix_retests_project_id'))

    op.drop_table('retests')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))

    op.drop_table('reports')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_vuln_class'))
        batch_op.drop_index(batch_op.f('ix_findings_target_id'))
        batch_op.drop_index(batch_op.f('ix_findings_repository_id'))
        batch_op.drop_index('ix_findings_project_status_severity')
        batch_op.drop_index(batch_op.f('ix_findings_project_id'))
        batch_op.drop_index(batch_op.f('ix_findings_engine_fingerprint'))

    op.drop_table('findings')
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_scan_id'))
        batch_op.drop_index('ix_dependencies_name')

    op.drop_table('dependencies')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_status'))
        batch_op.drop_index(batch_op.f('ix_scans_repository_id'))
        batch_op.drop_index(batch_op.f('ix_scans_project_id'))
        batch_op.drop_index('ix_scans_project_created')

    op.drop_table('scans')
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_runs_target_id'))
        batch_op.drop_index(batch_op.f('ix_test_runs_status'))
        batch_op.drop_index(batch_op.f('ix_test_runs_project_id'))

    op.drop_table('test_runs')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_repository_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_project_id'))

    op.drop_table('snapshots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_org_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_project_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_project_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_organization_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_project_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_organization_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('ai_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_targets_project_id'))

    op.drop_table('ai_targets')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('security_tests', schema=None) as batch_op:
        batch_op.drop_index('uq_security_tests_org_key', postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))
        batch_op.drop_index('uq_security_tests_builtin_key', postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_security_tests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_security_tests_category'))

    op.drop_table('security_tests')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    op.drop_table('users')
    op.drop_table('organizations')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_run_after')

    op.drop_table('jobs')
    # ### end Alembic commands ###
